### PR TITLE
Remove some garbage record creation.

### PR DESCRIPTION
**Pull request by cxmcc**
@kwent 
This will remove some of the records that no one cares about, such as `*.sg.*` and elb records.
We can minimize the change set to make it easier to debug.

### CODE REVIEW

**Comment by solidsnack** [comment]
Maybe you guys would like Dr. DNS? It uses the power of serverless to simplify record creation.

https://github.com/solidsnack/drdns

No need for a cron job...

Would be happy to swing by and demo it.

**Comment by cxmcc** [comment]
Hey @solidsnack ! Thanks for the suggestion. That's a good idea, @kwent and I have discussed the exact same idea!
We are only using zonify for some legacy nodes. I can imagine we will very likely downplay the need for dns names to instances/autoscaling groups going forward. There are better ways for service discovery (autoscaling group -> elb -> dns name, etc).

Also we noticed event-based dns name creation/deletion also has a critical flaw -- if the action fails for whatever reason (such as rate limit), there will be orphan records or records missing. The lambda event handler *alone* is not a reliable solution that can be trusted by key infrastructure components.

**Comment by solidsnack** [comment]
The "diffing" method performed by Zonify does have a significant advantage
in reliability but also soaks up more API calls. Lambda's automatic retries
mitigate the concern about orphan records somewhat.

Dr. DNS could apply the diffing algorithm on every event (for example) for
greater precision. It will run for longer but Lambda is very cheap.

Zonify was not really intended for service discovery, but rather for
simplifying the developer experience -- being able to name machines is
helpful when later trying to connect to them. DNS names also allow SSH
policies to be set and constrained to the correct domain. I don't think the
update speed of Zonify would be acceptable for all but the coarsest service
discovery needs.
Xiuming Chen <notifications@github.com> schrieb am Mi. 14. Juni 2017 um
18:21:

**Comment by cxmcc** [comment]
Here are some of my major concerns for approach like this.
1) inconsistent user experience. When users try to ssh into `console.domain`, it picks a node with `*.console.domain`. It's a form of service discovery for developers. It appears to be convenient and useful. As a result it gives a false sense of safety to developer to rely on using it in their production services (it happened!). When we were using zonify, the experience has not been consistent. We saw missing and orphan and outdated records (mostly because rate limit problem becomes obvious in a cluster with more than a few nodes). Even just for dev experience, it creates confusion and mistrust whenever developers find out the dns name leads to a wrong place.
2) exhausting rate limit. I am sure using lambda and retrying a few time may be fine for many use cases, but its reliability remains questionable when a system is scaling up and down rapidly. Exhausting the rate limit isn't great, it negatively affects good players in our system sharing the same limit. Adding and removing dns records all the time may not be the right solution at our scale. IMHO removing moving parts like this helps improve stability.

**Comment by solidsnack** [comment]
Regarding (1) specifically: it is not clear that this convenience will
always be used incorrectly. It is only likely to be used if there is no
good alternative.
Xiuming Chen <notifications@github.com> schrieb am Do. 15. Juni 2017 um
01:00:

**Pull request merged**
